### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dirkdirk084474** [learn-co-curriculum/creating-and-inserting-dom-nodes#13]
Entering the following code into the console returns a Syntax error (indicated below the code)

const divs = document.querySelectorAll('div')
function capture(e) {
  console.log(this.firstChild.nodeValue.trim() + ' captured')
}
for (let i = 0; i < divs.length; i++) {
  divs[i].addEventListener('click', capture, true)
}

Uncaught SyntaxError: Identifier 'divs' has already been declared
    at <anonymous>:1:1

**Comment by gj** [comment]
Hi @coryallen01 !

When you use `const` and `let`, you can only declare a variable once in a given scope. Since you're in the console, just refresh the page and your browser will flush all previously-declared variables, giving you a fresh scope.
