### ISSUE TITLE
creating and inserting dom nodes shows right menu of lab, not reading

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/creating-and-inserting-dom-nodes#14]
To reproduce:
1. Go to https://learn.co/tracks/web-development-immersive-2-0-module-three/javascript-foundations/the-dom/creating-and-inserting-nodes
2. Note that right menu is a lab format with "fork, test, submit" pattern
3. Open related Github repo: https://github.com/learn-co-curriculum/creating-and-inserting-dom-nodes
4. Note there are no tests to pass and thus lab cannot be completed

![screen shot 2017-10-12 at 11 08 43 am](https://user-images.githubusercontent.com/10333387/31503489-c9d76a82-af3d-11e7-81a9-ed61d4b12465.png)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
