### ISSUE TITLE
There is not a open Learn IDE button

### ISSUE THREAD

**Issue by haeke** [learn-co-curriculum/creating-and-inserting-dom-nodes#18]
Hello,

The open IDE button is missing from this project? I was curious to know if this is intentional.

Thank you,

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @haeke.

We have updated the materials so this lesson registers as a code along with an open ide button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
