### ISSUE TITLE
"Open" button unavailable on the site. 

### ISSUE THREAD

**Issue by Tsifu** [learn-co-curriculum/creating-and-inserting-dom-nodes#2]
Unable to access the lab with the blue "Open" on the website.  Thanks.

**Comment by AnnJohn** [comment]
hi @Tsifu please use the fork icon on the right side of the page to fork the lab. 

If this is still an issue, please file a bug report as this is a product issue. thanks!

**Comment by braden337** [comment]
@AnnJohn This lesson is just a readme, but it's setup like a lab on learn.co, so there is no way to "finish reading"

Same problem with the Traversing Nested Objects lesson
