### ISSUE TITLE
This lesson should be a lab

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/creating-and-inserting-dom-nodes#21]
@maxwellbenton 
In order for a student to follow along with this lesson, they need to open the  sandbox, manually clone the repo, and then run httpserver - it is a lot just for a codealong. I think it would be easier if we used the "Open IDE" button here instead.

**Comment by d-d-d-dalia** [comment]
Seconding this. The lesson says to open the index.html file, but there is no open ide button to fork/clone the repo.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kwebster2 and @d-d-d-dalia.

We've added a folder and an optional index.js file that should cause learn.co to register this as a code along for any future students.
