### ISSUE TITLE
What am I supposed to do?

### ISSUE THREAD

**Issue by Kngo93** [learn-co-curriculum/creating-and-inserting-dom-nodes#23]
What exactly am I supposed to do for this module? How do I access the tests within the IDE? And how do I submit? I'm typing the normal commands I've been using in index.js but nothing is happening.

**Comment by maxwellbenton** [comment]
Hi @Kngo93,

Thank you for providing this feedback. This lesson is designed as a code-along, requiring changes to the file contents of the lesson before Learn will consider the lesson completed. We've updated the instructions to this lesson to provide further guidance on how to register completion, which should resolve this issue. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience so we can improve our content for future students.

Thank you!
