### ISSUE TITLE
Unable to complete.

### ISSUE THREAD

**Issue by AmariEllington** [learn-co-curriculum/creating-and-inserting-dom-nodes#26]
Unable to complete this module as there are not test set up for students to complete.

**Comment by jasminnancy** [comment]
You just need to follow along with the README then type "learn submit"
Once you've submitted, then you need to press the "I'm done" button on learn and you can finish the lab!

**Comment by maxwellbenton** [comment]
Hi @AmariEllington,

Thank you for providing this feedback. This lesson requires students to follow along, making changes to the file contents of the lesson. We've updated the instructions to this lesson to provide further guidance on how to register completion in this lab, which should resolve this issue. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience so we can improve our content for future students.

Thank you!
