### ISSUE TITLE
Ruby error when executing "learn test" command

### ISSUE THREAD

**Issue by itwebdeveloper** [learn-co-curriculum/creating-and-inserting-dom-nodes#27]
Software: Learn IDE 3
O/S: Windows 10

Reproduction steps:

1. Type "learn test" on the console;
2. Press Enter;

Result:

```
/usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wifelette** [comment]
There's no test suite here, so this makes sense. The issue should probably be that the instructions should start with making that clear.

**Comment by justinamaple** [comment]
This is very unclear, since you basically have to run "learn submit" without writing any code. 

In my opinion, the simplest solution would be to just remove any submission from this "lab" since all you are doing is running the code segments given to you.

**Comment by maxwellbenton** [comment]
Hi @itwebdeveloper,

Thank you for providing this feedback. While there are no tests, these lessons are designed to provide hands-on practice and require some change to the file contents. We've updated this lesson to include clearer instructions that this is a code-along requiring changes to files in the repository and `learn submit` to register completion. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!

**Comment by RefinedSilver** [comment]
I know this issue was closed, but this particular Lab won't clear without examining this error message. As a new coder, I am very curious to know how to read what is going on within this error message if anyone has some guidance.

/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/test/index-test.js:1
import { expect } from 'chai';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
    at Module._compile (internal/modules/cjs/loader.js:1140:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/mocha.js:421:19)
    at singleRun (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/mocha/lib/cli/run.js:366:11)
    at /Users/brianjones/Development/code/react-static-components-lab-nyc04-seng-ft-041920/node_modules/yargs/lib/command.js:241:49
~/.../code/react-static-components-lab-nyc04-seng-ft-041920 // ♥ > Traceback (most recent call last):
        11: from /Users/brianjones/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /Users/brianjones/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /Users/brianjones/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /Users/brianjones/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
         6: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
         5: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
         4: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
         3: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
         2: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/Users/brianjones/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
~/.../code/react-static-components-lab-nyc04-seng-ft-041920 // ♥ > 

Here's the exercise from which it came:

https://learn.co/tracks/module-4-web-development-immersive-2-1/v2-introduction-to-react/introduction-to-react/a-react-app-example
